name: lyrics
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex
  - aom
  - bzip2
  - ca-certificates
  - expat=2.5.0
  - ffmpeg=5.1.2
  - font-ttf-dejavu-sans-mono
  - font-ttf-inconsolata
  - font-ttf-source-code-pro
  - font-ttf-ubuntu
  - fontconfig
  - fonts-conda-ecosystem
  - fonts-conda-forge
  - freetype
  - gettext
  - icu
  - lame
  - libffi
  - libflac
  - libiconv
  - libllvm11
  - libogg
  - libopus
  - libpng
  - libsndfile
  - libsqlite
  - libvorbis
  - libxcb
  - libxml2
  - libzlib
  - mpg123
  - openh264
  - openssl
  - pthread-stubs
  - python
  - python_abi
  - svt-av1
  - tk
  - tzdata
  - x264
  - x265
  - xorg-fixesproto
  - xorg-kbproto
  - xorg-libx11
  - xorg-libxau
  - xorg-libxdmcp
  - xorg-libxext
  - xorg-libxfixes
  - xorg-xextproto
  - xorg-xproto
  - xz
  - pip
  - pip:
      - absl-py==1.4.0
      - libdrm
      - libnsl
      - readline
      - p11-kit
      - _openmp_mutex
      - gmp
      - gnutls
      - libuuid
      - libgomp
      - libtasn1
      - libstdcxx-ng
      - libva
      - libvpx
      - libidn2
      - libunistring
      - libpciaccess
      - ncurses
      - nettle
      - ld_impl_linux-64
      - libgcc-ng
      - anyio==3.6.2
      - appdirs==1.4.4
      - astunparse==1.6.3
      - audioread==3.0.0
      - cachetools==5.3.0
      - certifi==2022.12.7
      - cffi==1.15.1
      - charset-normalizer==3.0.1
      - click==7.1.2
      - decorator==5.1.1
      - ffmpeg-python==0.2.0
      - filelock==3.9.0
      - flatbuffers==23.1.21
      - future==0.18.3
      - gast==0.4.0
      - google-auth==2.16.0
      - google-auth-oauthlib==0.4.6
      - google-pasta==0.2.0
      - grpcio==1.51.1
      - h11==0.12.0
      - h2==4.1.0
      - h5py==3.8.0
      - hpack==4.0.0
      - httpcore==0.13.7
      - httpx==0.19.0
      - huggingface-hub==0.12.0
      - hyperframe==6.0.1
      - idna==3.4
      - joblib==1.2.0
      - keras==2.11.0
      - libclang==15.0.6.1
      - librosa==0.8.1
      - llvmlite==0.38.1
      - markdown==3.4.1
      - markupsafe==2.1.2
      - more-itertools==9.0.0
      - norbert==0.2.1
      - numba==0.55.2
      - numpy==1.22.4
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cudnn-cu11==8.5.0.96
      - oauthlib==3.2.2
      - openai-whisper==20230124
      - opt-einsum==3.3.0
      - packaging==23.0
      - pandas==1.5.3
      - pooch==1.6.0
      - protobuf==3.19.6
      - pyasn1==0.4.8
      - pyasn1-modules==0.2.8
      - pycparser==2.21
      - python-dateutil==2.8.2
      - pytz==2022.7.1
      - pyyaml==6.0
      - regex==2022.10.31
      - requests==2.28.2
      - requests-oauthlib==1.3.1
      - resampy==0.4.2
      - rfc3986==1.5.0
      - rsa==4.9
      - scikit-learn==1.2.1
      - scipy==1.10.0
      - setuptools==67.2.0
      - six==1.16.0
      - sniffio==1.3.0
      - soundfile==0.11.0
      - spleeter==2.3.2
      - tensorboard==2.11.2
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - tensorflow==2.11.0
      - tensorflow-estimator==2.11.0
      - tensorflow-io-gcs-filesystem==0.30.0
      - termcolor==2.2.0
      - threadpoolctl==3.1.0
      - tokenizers==0.13.2
      - torch==1.13.1
      - tqdm==4.64.1
      - transformers==4.26.0
      - typer==0.3.2
      - typing-extensions==4.4.0
      - urllib3==1.26.14
      - werkzeug==2.2.2
      - wheel==0.38.4
      - wrapt==1.14.1